title: Táborská setkání
nextEvent: '2021-09-10T12:47:37.254Z'
lang: cs
twitter:
facebook: https://www.facebook.com/taborskasetkani
instagram:
translate: https://static-taborskasetkani-eu.translate.goog/?_x_tr_sl=cs&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp
cdn: https://modurad.otevrenamesta.cz/media/mutabor
cdnapi: https://modurad.otevrenamesta.cz/cdn
globalComponents:
  triangleWrapper: triangleWrapper.js
#  DynamicForm: dynamicForm.js
menu:
  - label: Program
    link: "/program"
  - label: Vstupné
    link: "/vstupne"
  - label: Info
    link: "/info"
    children:
      - label: Návštěvníci
        link: "/info/navstevnici"
      - label: Obyvatelé
        link: "/info/obyvatele"
      - label: Média
        link: "/info/media"
      - label: Výběrová řízení
        link: "/info/vyberka"
  - label: Partneři
    link: "/partneri"
  - label: Galerie
    link: "/galerie"
  - label: Kontakt
    link: "/kontakt"
detailpages:
  - path: /posts/
    url: https://modurad.otevrenamesta.cz/mutabor/uni/ts_posts/?filter={"id":"{{ID}}"}
    layout: postDetail
    titleattr: title
  - path: /galerie/
    url: https://modurad.otevrenamesta.cz/mutabor/uni/ts_rocniky/?filter={"title":"{{ID}}"}
    layout: rocnikDetail
    titleattr: title
    children:
    - component: eventgallery
      url: https://modurad.otevrenamesta.cz/mutabor/mediaman
