- name: list
  label: Seznam obrázků
  component: dyn-listeditor
  form:
  - name: url
    component: FileUploadingSelect
    label: Obrazek
    default_tags: partneri
    fileindex_url: /uniapi/files
    tag_url: /uniapi/filetags
    storage_url: /cdn/
    rules: required
  - name: name
    component: dyn-input
    label: Název
  - name: web
    component: dyn-input
    label: Webove stranky
  - name: width
    component: dyn-input
    label: Šířka obrázku v pixelech