- name: list
  label: Seznam obrázků
  component: dyn-listeditor
  form:
  - name: url
    component: dyn-input
    label: Odkaz
    rules: required
  - name: name
    component: dyn-input
    label: Název
  - name: web
    component: dyn-input
    label: Webove stranky
